### ISSUE TITLE
tutorial12

### ISSUE THREAD

**Issue by faerytea** [triplepointfive/ogltutor#1]
... Хотя, вспомним, что нет никакой разницы, ведь мы преобразуем координаты проекции в экран, поэтому позиция камеры не играет роли.

[](/images/t12_FOV.png“>

Начнем мы с определения расстояния плоскости проекции до камеры. ...

Поправьте скобочки для отображения картинки

**Comment by triplepointfive** [comment]
Пофиксил, спасибо!
